name: radar312
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiobotocore=2.25.2=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h5d8c7f2_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - arm_pyart=2.1.1=py312h4c3975b_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - botocore=1.40.70=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.2.0=py312h3dd09e2_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.25.0=py312hf79963d_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py312h4f23490_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - cmweather=0.3.2=pyhd8ed1ab_1
  - contourpy=1.3.3=py312hd9148b4_3
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py312h4c3975b_1
  - dask=2025.12.0=pyhcf101f3_0
  - dask-core=2025.12.0=pyhcf101f3_1
  - distributed=2025.12.0=pyhcf101f3_1
  - expat=2.7.3=h7354ed3_4
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fonttools=4.61.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gdal=3.12.1=py312hf50df08_0
  - geos=3.14.1=h480dda7_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py312ha4f8f14_101
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lat_lon_parser=1.3.1=pyhd8ed1ab_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libarrow=21.0.0=h56a6dad_8_cpu
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal-core=3.12.1=hf05ffb4_0
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=h6cb5226_4
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_8_cpu
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxml2-devel=2.15.1=he237659_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py312h3d67a73_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - minizip=4.0.10=h05a5f5f_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - multidict=6.7.0=py312h8a5da7c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - narwhals=2.15.0=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - netcdf4=1.7.3=nompi_py312hf6400b3_100
  - nlohmann_json=3.12.0=h54a6638_1
  - open-radar-data=0.5.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=haa7fec5_0
  - pillow=11.3.0=py312h7b42cdd_3
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.1=h99ae125_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.2.1=py312h5253ce2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py312h7900ff3_1
  - pyarrow-core=21.0.0=py312hc195796_1_cpu
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.7.2=py312h9b6a7d9_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - qhull=2020.2=h434a139_5
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.5.26=h5ac9029_0
  - s3fs=2026.1.0=pyhd8ed1ab_0
  - scipy=1.16.3=py312h54fa4ab_2
  - setuptools=80.9.0=py312h06a4308_0
  - setuptools-scm=9.2.2=pyhd8ed1ab_0
  - setuptools_scm=9.2.2=hd8ed1ab_0
  - shapely=2.1.2=py312h383787d_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.1=he0a8d7e_0
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py312h961da02_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - versioneer=0.29=pyhd8ed1ab_0
  - wheel=0.45.1=py312h06a4308_0
  - wrapt=1.17.3=py312h4c3975b_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xerces-c=3.3.0=hd9031aa_1
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xradar=0.10.0=pyhd8ed1ab_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py312h8a5da7c_0
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - comm==0.2.3
      - debugpy==1.8.19
      - decorator==5.2.1
      - deprecation==2.1.0
      - dm-tree==0.1.9
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jsmin==3.0.1
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - keras==3.13.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - metpy==1.7.1
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - nmc-met-io==0.1.15.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.18.0
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydda==2.2.0
      - pygments==2.19.2
      - pysteps==1.19.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-probability==0.25.0
      - termcolor==3.3.0
      - tf-keras==2.20.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - wradlib==2.6.1
prefix: /home/wjzhu/miniconda3/envs/radar312
